### PR TITLE
Updates for USB DVRs and Overriding comskip.sh

### PR DESCRIPTION
**Pull request by jvonhoff**
I added a couple of scripts to the s6 init folder, so that when the container restarts, it automatically takes ownership of /dev/dvb, as well as some other folders.  This was stolen from @WyseNynja's fork.

I also added another script to see if the user has their own comskip.sh in the /config path, and if so, symlink to it.  This allows me to do things like transcode to 480p for my kids' shows, so I'm not storing 2GB files of Curious George episodes.

### CODE REVIEW

**Comment by BlinkyStitt** [comment]
Why do you need to chown /dev/dvb? My recordings seem to be working fine without it. Also, I learned that the s6-overlay has fix-perms script thing in it but I couldn't find documentation for it and what I'd written works so I stayed with what I had .

Can you explain more about how you have different configs for different shows? I would also like to drop the quality on my cartoons.

**Comment by jvonhoff** [comment]
WRT, chowning /dev/dvb, I'm trying to run each service (plex, sonarr, etc) as its own user, and, as such, use the UID/GID parameters when I start up services like Plex.  Doing this, however, my /dev/dvb (root:video) would never get the permissions correct so that my WinTV-DualHD could be found.  I'd have to reset them (chown) and delete/re-add the tuner.  I doubt it's an issue if you're using the SiliconDust tuners, since they're network-based.  And it might not be an issue if you're not using UID/GID.  But, I am, and this was the best way I found to fix it so that it persists containers getting restarted, etc.

As for the script, I'm just grepping for folder names when I transcode for now.  Most of what I record goes into /Kids/ or /KidsTV/, so I can just push all that to 480p.  My current script is [here](https://github.com/jvonhoff/pms-docker).

**Comment by BlinkyStitt** [comment]
Thanks! It sounds like we have very similar setups. I wonder why my plex is able to use /dev/dvb and /dev/dri without the chown.  The network based tuners definitely sound like easier setup, but I think I’m happy with my QuadHD (besides having to set it up as two DualHDs).

Next up I’m going to try to add this: https://ryanfb.github.io/etc/2017/03/13/automatic_subtitle_extraction_for_plex_dvr.html <https://ryanfb.github.io/etc/2017/03/13/automatic_subtitle_extraction_for_plex_dvr.html>

**Comment by jvonhoff** [comment]
> wonder why my plex is able to use /dev/dvb and /dev/dri without the chown

Is your host Ubuntu, by chance?  I wondered if the group IDs were the same inside & outside the container, no chown would be necessary.  For Arch Linux, video is GID 91, but I think it's 40 in Ubuntu.

I envy your QuadHD, particularly with football season coming up.  But, for now, I'm just trying to get the 2nd tuner going on an Arch install... I keep holding out hope that every kernel upgrade will include the patches to make the 2nd one turn on!

**Comment by BlinkyStitt** [comment]
I'm running debian. The uid I'm using isn't actually in the video group. It does seem like it should need to be though.

**Comment by mandreko** [comment]
Sorry, I didn't see this until now. Was it closed due to inactivity or did you find a better methodology to what you were doing? I'm taking a look now. I agree with @WyseNynja that the network tuners are way easier to get working. I have an HD HomeRun working for me, so I hadn't had to worry about the permissions on a device.

**Comment by jvonhoff** [comment]
I closed it & just maintained it in my own repo -- I had a few changes after the pull request, and wanted to get the build automated with Docker Hub.

**Pull request closed without merging**
